# Generated by Django 4.2.9 on 2024-02-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employerAccount', '0005_customemployeruser_code_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('horaires', models.CharField(max_length=500)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerAccount.customemployeruser')),
            ],
        ),
    ]
