# Generated by Django 4.0 on 2024-01-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0007_remove_customuser_actualactivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='genPres',
            new_name='general_presentation',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='threeExperiences',
            new_name='three_experiences',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='threeGoodPoints',
            new_name='three_good_points',
        ),
    ]
