# Generated by Django 4.0 on 2024-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerAccount', '0002_customemployeruser_delete_employeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeruser',
            name='nb_siret',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
