# Generated by Django 4.0 on 2024-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerAccount', '0003_alter_customemployeruser_nb_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeruser',
            name='nb_siret',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
