# Generated by Django 4.2.9 on 2024-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerAccount', '0004_alter_customemployeruser_nb_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemployeruser',
            name='code_postal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customemployeruser',
            name='libelle_de_voie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customemployeruser',
            name='nom_enseigne',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customemployeruser',
            name='ville',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customemployeruser',
            name='nb_siret',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
