# Generated by Django 4.2.9 on 2024-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerAccount', '0005_customemployeruser_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemployeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customemployeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customemployeruser',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
